name: kosmokopy
version: '0.1.0'
summary: GTK4 file copier/mover with filtering and progress
description: |
  Kosmokopy recursively copies or moves files between directories
  with glob-based exclusion, progress tracking, and transfer-mode
  selection (files only or preserving folder structure).
  Select individual files or entire folders as the source.

base: core24
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

parts:
  kosmokopy:
    plugin: rust
    source: .
    build-packages:
      - libgtk-4-dev
      - libglib2.0-dev
      - libgraphene-1.0-dev
      - libcairo2-dev
      - libpango1.0-dev
      - libgdk-pixbuf-2.0-dev
    stage-packages:
      - libgtk-4-1
      - libglib2.0-0t64
      - libgraphene-1.0-0
      - libcairo2
      - libpango-1.0-0
      - libgdk-pixbuf-2.0-0

apps:
  kosmokopy:
    command: bin/kosmokopy
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - x11
